name 'sourcesense_liferay'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sourcesense_liferay'
long_description 'Installs/Configures sourcesense_liferay'
version '0.1.0'

depends 'sourcesense_mysql'
depends 'selinux'
depends 'ark'
depends 'docker'
